export const goods = [
  {
    id: '001',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/d61/370_416_1/49204940299.jpg',
    price: 6999,
    title: 'Футболка мужская Nike Zenit Saint Petersburg 2021/22 Stadium Home',
    description: 'Футбольное джерси из домашней формы ФК "Зенит" — отличный выбор для болельщиков.',
    number: 82,
  },
  {
    id: '002',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/880/370_416_1/52059790299.jpg',
    price: 5999,
    title: 'Домашняя футболка ФК Локомотив мужская, adidas',
    description: 'Пусть все знают, за кого ты болеешь! Футбольное джерси adidas полностью повторяет дизайн домашней формы ФК "Локомотив".',
    number: 33,
  },
  {
    id: '003',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/b70/370_416_1/49896050299.jpg',
    price: 7999,
    title: 'Футболка мужская adidas 2021/2022 Arsenal FC Home',
    description: 'Поддерживай любимый клуб в футбольном джерси adidas Arsenal 21/22.',
    number: 0,
  },
  {
    id: '004',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/048/370_416_1/51124610299.jpg',
    price: 7699,
    title: 'Футболка мужская Nike Inter Milan 2021/22 Stadium Home',
    description: 'Футбольное джерси из домашней формы ФК "Милан". Реплика формы, в которой выступают профессиональные игроки.',
    number: 5,
  },
  {
    id: '005',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/bb8/370_416_1/51331790299.jpg',
    price: 7499,
    title: 'Футболка мужская PUMA BVB Home',
    description: 'Эта футболка от PUMA — дань уважения победе команды "Боруссия-Дортмунд" 27 мая 1997 года в матче против явного фаворита "Ювентус". Она выполнена в официальных цветах клуба и декорирована эмблемой ФК "Боруссия-Дортмунд".',
    number: 5,
  },
  {
    id: '006',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/d89/370_416_1/51331770299.jpg',
    price: 7499,
    title: 'Футболка мужская PUMA MCFC Home',
    description: 'Футболка для домашних игр ФК "Манчестер Сити". Модель декорирована официальной эмблемой клуба и имеет ярлык с обозначением лицензионного продукта.',
    number: 51,
  },
  {
    id: '007',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/249/370_416_1/50118080299.jpg',
    price: 7299,
    title: 'Футболка мужская Nike Atletico Madrid 2021/22 Stadium Home',
    description: 'Футбольное джерси Nike из коллекции Stadium повторяет дизайн формы, в которой выступают игроки ФК "Атлетико Мадрид".',
    number: 18,
  },
  {
    id: '008',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/08e/370_416_1/51509880299.jpg',
    price: 7499,
    title: 'Футболка мужская PUMA ACM Home',
    description: 'Футболка для домашних игр с логотипом ФК "Милан.',
    number: 7,
  },
  {
    id: '009',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/d1c/370_416_1/50805780299.jpg',
    price: 7999,
    title: 'Футболка мужская adidas FC Bayern Home',
    description: 'Кто главные герои футбольного матча: игроки на поле или фанаты на трибунах? Очевидно, что без одних не было бы и других. Поддерживай и будь активным участником жизни клуба в джерси adidas FC Bayern.',
    number: 99,
  },
  {
    id: '010',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/567/370_416_1/45428200299.jpg',
    price: 7299,
    title: 'Футболка мужская Nike FC Barcelona 2021/22 Stadium Home',
    description: 'Футбольное джерси Nike из домашней формы ФК "Барселона" — отличный способ поддержать любимую команду.',
    number: 24,
  },
  {
    id: '011',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/79b/370_416_1/44904040299.jpg',
    price: 7299,
    title: 'Футболка мужская Nike Paris Saint-Germain 2021/22 Stadium Home',
    description: 'Футбольное джерси из домашней формы команды Paris Saint-Germain. Реплика формы, в которой выступают профессиональные игроки.',
    number: 0,
  },
  {
    id: '012',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/56a/370_416_1/46625510299.jpg',
    price: 7299,
    title: 'Футболка мужская Nike Liverpool FC 2021/22 Stadium Home',
    description: 'Футбольное джерси Nike в стиле домашней формы ФК "Ливерпуль". Реплика формы, в которой выступают профессиональные игроки, позволит поддержать любимую команду.',
    number: 71,
  },
  {
    id: '013',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/275/370_416_1/45671880299.jpg',
    price: 7999,
    title: 'Футболка мужская adidas Real Madrid 21/22 Home Jersey',
    description: 'Празднуй победы своего любимого клуба в футбольном джерси adidas Real Madrid, созданном специально для фанатов. Дизайн модели посвящен одной из самых ярких достопримечательностей Мадрида — площади Сибелес.',
    number: 5,
  },
  {
    id: '014',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/762/370_416_1/46629440299.jpg',
    price: 7999,
    title: 'Футболка мужская adidas Juventus 21/22 Home',
    description: 'Футбольное джерси adidas Juventus посвящено 1-летию домашней арены клуба "Ювентус" — легендарного стадиона "Альянц Стадиум".',
    number: 2,
  },
  {
    id: '015',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/76c/370_416_1/49522000299.jpg',
    price: 7999,
    title: 'Футболка мужская adidas 21/22 Manchester United Home',
    description: 'Поддерживай любимую команду в джерси adidas Manchester United 21/22, которое создано по мотивам легендарной домашней формы клуба, принесшей "Манчестер Юнайтед" много ярких побед!',
    number: 15,
  },
  {
    id: '016',
    img: 'https://cdn.sptmr.ru/upload/resize_cache/iblock/cd8/370_416_1/37503790299.jpg',
    price: 2999,
    title: 'Футболка мужская Nike Spartak Moscow 2020/21 Stadium Home',
    description: 'Футболка Spartak Moscow Stadium Home позволит чувствовать себя комфортно на поле. Дизайн модели разработан на основе формы для домашних игр футбольного клуба "Спартак".',
    number: 44,
  },
]
